# Generated by Django 3.2.25 on 2024-05-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_currencymining_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Электронный адрес'), ('vk', 'Вконтакте'), ('tg', 'Телеграм'), ('link', 'Электронынй ресурс')], max_length=50, verbose_name='Еденица измерения')),
            ],
            options={
                'verbose_name': 'Хешрейт',
                'verbose_name_plural': 'Хешрейт',
            },
        ),
    ]
