# Generated by Django 3.2.25 on 2024-05-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxygroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': '2. Группы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '1. Пользователи'},
        ),
    ]
