# Generated by Django 3.2.25 on 2024-05-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Оплачен'), (3, 'Отменён')], default=1, verbose_name='Статус заказа'),
        ),
    ]
